# Generated by Django 4.2.4 on 2023-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="movie_list",
            field=models.ManyToManyField(
                related_name="users_with_movie_in_list", to="films.movie"
            ),
        ),
    ]
